- name: Install dependencies & PSPSDK
        run: |
          sudo apt-get update
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          sudo apt-get install -y --fix-missing \
            build-essential cmake pkgconf libreadline8 libusb-0.1 libgpgme11 libarchive-tools fakeroot wget
          wget https://github.com/pspdev/pspdev/releases/latest/download/pspdev-ubuntu-latest-x86_64.tar.gz
          tar -xzf pspdev-ubuntu-latest-x86_64.tar.gz
          echo "PSPDEV=$HOME/pspdev" >> $GITHUB_ENV
          echo "PATH=$HOME/pspdev/bin:$PATH" >> $GITHUB_ENV
