name: Build PSP game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies & PSPSDK
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkgconf libreadline8 libusb-dev libgpgme-dev libarchive-tools fakeroot wget
          wget https://github.com/pspdev/pspdev/releases/latest/download/pspdev-ubuntu-latest-x86_64.tar.gz
          tar -xzf pspdev-ubuntu-latest-x86_64.tar.gz
          mkdir -p $HOME/pspdev
          mv pspdev/* $HOME/pspdev/
          echo "PSPDEV=$HOME/pspdev" >> $GITHUB_ENV
          echo "PATH=$HOME/pspdev/bin:$PATH" >> $GITHUB_ENV

      - name: Build PSP game
        run: |
          echo "Current PATH: $PATH"
          make

      - name: List all files after build
        run: find . -type f

      - name: Upload PBP artifact
        uses: actions/upload-artifact@v4
        with:
          name: psp-game-pbp
          path: "**/EBOOT.PBP"
