name: Build PSP Game

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies & PSPSDK
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkgconf libreadline8 libusb-dev libgpgme-dev libarchive-tools fakeroot wget git
          mkdir -p $HOME/pspdev
          wget https://github.com/pspdev/pspdev/releases/latest/download/pspdev-ubuntu-latest-x86_64.tar.gz
          tar -xzf pspdev-ubuntu-latest-x86_64.tar.gz -C $HOME/pspdev --strip-components=1

          echo "Cek isi folder bin PSPDEV"
          ls -l $HOME/pspdev/bin
          ls -l $HOME/pspdev/psp/bin

          echo "Cek apakah psp-gcc ada dan bisa dijalankan"
          $HOME/pspdev/bin/psp-gcc --version || echo "psp-gcc tidak ditemukan!"

      - name: Build PSP Game
        env:
          PSPDEV: ${{ env.HOME }}/pspdev
          PSPSDK: ${{ env.HOME }}/pspdev/psp/sdk
          PATH: ${{ env.HOME }}/pspdev/bin:${{ env.HOME }}/pspdev/psp/bin:/usr/bin:/bin:${{ env.PATH }}
        run: |
          echo "Current PATH: $PATH"
          make

      - name: Upload EBOOT.PBP
        uses: actions/upload-artifact@v4
        with:
          name: psp-game-pbp
          path: "**/EBOOT.PBP"
