name: Build PSP game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies & PSPSDK
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkgconf libreadline8 libusb-dev libgpgme-dev libarchive-tools fakeroot wget git
          wget https://github.com/pspdev/pspdev/releases/latest/download/pspdev-ubuntu-latest-x86_64.tar.gz
          tar -xzf pspdev-ubuntu-latest-x86_64.tar.gz
          mkdir -p $HOME/pspdev
          mv pspdev/* $HOME/pspdev/

      - name: Install pack-pbp manually
        run: |
          git clone --depth=1 https://github.com/pspdev/psptoolchain-extra.git
          cd psptoolchain-extra/tools/pack-pbp
          make
          mkdir -p $HOME/pspdev/bin
          cp pack-pbp $HOME/pspdev/bin/
          cd ../mksfo
          make
          cp mksfo $HOME/pspdev/bin/

      - name: Build PSP game
        env:
          PSPDEV: $HOME/pspdev
          PATH: $HOME/pspdev/bin:$HOME/pspdev/psp/bin:${{ env.PATH }}
        run: |
          echo "Current PATH: $PATH"
          make

      - name: List all files after build
        run: find . -type f

      - name: Upload PBP artifact
        uses: actions/upload-artifact@v4
        with:
          name: psp-game-pbp
          path: "**/EBOOT.PBP"
