- name: Build PSP game
  run: make

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies & PSPSDK
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkgconf libreadline8 libusb-0.1 libgpgme11 libarchive-tools fakeroot wget
          wget https://github.com/pspdev/pspdev/releases/latest/download/pspdev-ubuntu-latest-x86_64.tar.gz
          tar -xzf pspdev-ubuntu-latest-x86_64.tar.gz
          echo "PSPDEV=$HOME/pspdev" >> $GITHUB_ENV
          echo "PATH=$HOME/pspdev/bin:$PATH" >> $GITHUB_ENV

      - name: Build PSP game
        run: |
          make clean
          make

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: psp-game-pbp
          path: "*.pbp"
      
