name: Build PSP Game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y psp-sdk build-essential

      - name: Build PSP game
        run: |
          make clean
          make

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: psp-game-pbp
          path: "*.pbp"
